E (a + (A g W c)) U ((b & - d) + h) (* TRUE *)
A G (a + b + c + d + e + - f) (* TRUE *)
A F (A X (d + f + h + j)) (* FALSE *)
A G ((a & b) -> (b & c)) (* TRUE *)
E F k (* FALSE *)
E X j (* TRUE *)
A X a (* TRUE *)
E G (E F (g + h + i)) (* TRUE *)
⊥ (* FALSE *)
⊤ (* TRUE *)
(⊥ + (E G (a + c + e + g + i))) & (E X c) & ((A G (a + b + c)) ⊕ (E G a)) (* TRUE *)
A b W e (* FALSE *)
E (a + b) W j (* TRUE *)
